language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  # Make sure we're running a modern node install
  # http://austinpray.com/ops/2015/09/20/change-travis-node-version.html
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  # https://github.com/creationix/nvm#long-term-support
  - source ~/.nvm/nvm.sh && nvm install --lts
  # install packages and run postinstall processes
  - npm install

script:
  - python manage.py collectstatic --no-input
  - python manage.py check --fail-level=WARNING
  - python manage.py test
  - coverage run --source='.' manage.py test

after_success:
  - coveralls
